baseURL = "https://Susy-eng.github.io/vspace"
languageCode = "en-us"
theme = "anatole"
title = "Blog"

[params]
author = "Susy-eng"
description = "An online note space. - ğŸ‘©â€ğŸ’» Practice makes perfect.- ğŸ¤– A week is 2% of the year.- ğŸ¾ Doing something today that your future self will thank you for.- ğŸ‚ You only live once."
profilePicture = "images/profile.jpg"
doNotLoadAnimations = true # Animations are loaded by default
contentratio = 0.7

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"


copyright = "2024-{{ YEAR }}"